version: "3"

services:
  sqs:
    image: "roribio16/alpine-sqs"
    ports:
      - 9324:9324
      - 9325:9325
  minio:
    image: minio/minio
    command: ["server", "/data"]
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
