version: "3"

services:
  sqs:
    image: graze/sqs-local
    ports:
      - 9324:9324
    volumes:
      - ./elasticmq.conf:/elasticmq.conf
  minio:
    image: minio/minio
    command: ["server", "/data"]
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
  mongo-alpine:
    image: mvertes/alpine-mongo:3.6.5-0
    restart: always
    ports:
      - 27017:27017
