apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "article-hosting-importer.fullname" . }}
  labels:
    {{- include "article-hosting-importer.labels" . | nindent 4 }}
    app.kubernetes.io/component: importer
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      parallelism: 2
      template:
        metadata:
          labels:
            app.kubernetes.io/component: importer
        spec:
          restartPolicy: OnFailure
          containers:
          - name: importer
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            ports:
              - name: http
                containerPort: 32017
                protocol: TCP
            envFrom:
              - configMapRef:
                  name: importer-config
            env:
              - name: CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: document-db
                    key: connection-string
              - name: DOCDB_USER
                valueFrom:
                  secretKeyRef:
                    name: document-db
                    key: username
              - name: DOCDB_PASS
                valueFrom:
                  secretKeyRef:
                    name: document-db
                    key: password
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: importer-secrets
                    key: accesskey
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: importer-secrets
                    key: secretkey
